# secrets.toml

AWS_ACCESS_KEY = "your_aws_access_key_here"
AWS_SECRET_KEY = "your_aws_secret_key_here"
S3_BUCKET_NAME = "your_s3_bucket_name_here"

# OpenAI API key
API_KEY = "your_openai_api_key_here"
